### ISSUE TITLE
Can I use it to learn multiple games or predict multiple videos with the same network/system?

### ISSUE THREAD

**Issue by runvnc** [ogmacorp/OgmaNeo#21]
Hello, this is so interesting.  Could I use OgmaNeo to create a computer program that can learn to predict a video, then the same program/dataset (network?) learn to predict another video, and perhaps a third or more, where the same program/dataset is able to predict based on frames from these different videos?  So maybe it would need to select a context, or that would happen sort of transparently based on the properties of OgmaNeo..or not?

Similarly, could I use OgmaNeo to create an AI that can learn one game, and then train it on another similar game -- would anything transfer over?  Would it even be able to play both games equally well?

Thanks very much for any time you have for this question, and for publishing your work on this in general.

**Comment by 222464** [comment]
Hi!

We haven't tested per-task forgetting specifically yet, but since OgmaNeo is an online learning system that doesn't use any form of batching/experience replay, it should work reasonably well (hopefully). We use sparse representations to avoid forgetting, and these don't have a history window beyond which they forget, unlike something like experience replay.

Something would definitely transfer between tasks, the question is how much (I suspect a reasonable amount). If you would like to test this yourself, you can control the level of sparsity to have a generalization/forgetting tradeoff using the sfc_chunkSize or sfd_chunkSize parameters (higher chunk sizes means more sparse). The former is the relevant setting when using the chunk encoder, the latter is the relevant setting when using the distance encoder.

**Comment by runvnc** [comment]
Thanks for the detailed reply.  I may try testing that sort of thing in the
context of trying to create a more general purpose system.
